# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements
  - id: check-yaml
  - id: check-added-large-files
- repo: local
  hooks:
    - id: lint
      name: ruff linter
      entry: ruff check
      files: ^mlabican/
      language: system
      types: [python]

    - id: prettier
      name: ruff format - pretty code
      entry: ruff format
      files: ^mlabican/
      language: system
      types: [python]

    - id: unit-tests
      name: Unit tests w/ coverage
      entry: coverage run
      language: system
      pass_filenames: false
      verbose: true
      types: [python]

    - id: coverage
      name: Coverage Report
      entry: coverage report
      language: system
      pass_filenames: false
      verbose: true
      types: [python]
